"""Deterministic World IR -> Evennia compiler.

Whitepaper 03 (`docs/whitepapers/03-compilable-world-architecture.md`, section 1)
opens with the exact failure mode this module exists to avoid: letting an LLM
freehand-generate game code is unpredictable and hard to track. So this is a
plain, deterministic Python function — same World IR in, same `.ev` batch-command
file out, every time. The AI's job is producing and revising the World IR (which
*is* reviewable, diffable YAML); this compiler's job is turning validated World IR
into Evennia artifacts without reinterpreting anything.

Refuses to run on a world that hasn't passed `validate_world()` — compiling an
invalid world just moves the same bugs somewhere harder to read.

Batch-command semantics this compiler relies on — verified against the actual
Evennia source in D:\\Ai\\external-repos\\evennia\\evennia\\commands\\default\\building.py,
AND against a real batch-command run against a live Evennia server during
development (not assumed from memory or the docs alone — two real bugs only
showed up under an actual run, see notes below):

- `@dig <name>;<alias>` creates a room with NO exits when given no `=` clause —
  safe to run from anywhere, doesn't touch the caller's current location.
- `@open <exit> = <destination>`, `@create/drop <obj>`, and `@desc <target> =`
  all resolve their target via a LOCAL search (the caller's current location
  and inventory) — NOT a global lookup by id/alias. A freshly dug room is not
  in the caller's vicinity, so `@desc <room-id> = ...` fails with "could not
  find" unless the caller has actually teleported into that room first and the
  command targets `here`. This is why every per-room action (description,
  exits, characters, items) happens in one teleport-then-act block per room,
  not by referring to rooms by name from wherever the caller happens to be.
- `@teleport` (alias `@tel`) moves the caller.
- The `<name>[;alias][:typeclass]` syntax is whitespace-sensitive: a typeclass
  needs to immediately follow `:` with NO spaces around it
  (`rusted_key:objects.Key`, not `rusted_key : objects.Key`) — a space there
  breaks Evennia's own arg parser with an unrelated-looking AttributeError
  rather than a clean usage message, discovered the same way (a real run, not
  documentation).
- Rooms are dug with their World IR `id` as an alias (not just the human title)
  so the rest of the script can always `@tel <id>` / `@open ... = <id>`
  regardless of what the room's display name is.
"""
from __future__ import annotations

from pathlib import Path

from .schema import WorldIR
from .validate import validate_world


class CompileError(Exception):
    pass


def _room_ref(world: WorldIR, room_id: str) -> str:
    """The stable name to use when referring to a room in batch-commands —
    always the World IR id, which every dug room carries as an alias."""
    room = world.rooms.get(room_id)
    return room.id if room else room_id


def compile_batchcode(world: WorldIR) -> str:
    """Returns the contents of an Evennia batch-command (.ev) file."""
    report = validate_world(world)
    if not report.ok:
        raise CompileError(
            f"Refusing to compile an unvalidated world (world_id={world.id}): "
            f"{report.as_dict()['validation']}"
        )

    lines: list[str] = [
        f"# Generated by world_ir.compile_evennia — world '{world.id}' v{world.version}",
        f"# {len(world.rooms)} rooms, {len(world.exits)} exits, {len(world.characters)} characters,"
        f" {len(world.items)} items, {len(world.quests)} quests",
        "# Do not hand-edit; regenerate from the World IR instead.",
        "#",
        "# --- Phase 1: dig all rooms bare (no desc/exits yet — safe from any caller location) ---",
        "#",
    ]

    for room in world.rooms.values():
        name_part = f"{room.title};{room.id}" if room.title and room.title != room.id else room.id
        lines.append(f"@dig {name_part}")
        lines.append("#")

    # --- Phase 2: one @tel per room, then everything that belongs there (desc,
    # exits, characters, items) — all four need the caller physically "in" the
    # room because @desc/@open/@create-drop all resolve targets via local search.
    by_room: dict[str, dict[str, list]] = {rid: {"exits": [], "characters": [], "items": []} for rid in world.rooms}

    for ex in world.exits:
        by_room.setdefault(ex.from_room, {"exits": [], "characters": [], "items": []})["exits"].append(ex)

    unplaced_characters = []
    for char in world.characters.values():
        if char.role == "player_start":
            continue  # see note below — not instantiated as a batch-command object
        if char.location and char.location in world.rooms:
            by_room[char.location]["characters"].append(char)
        else:
            unplaced_characters.append(char)

    unplaced_items = []
    for item in world.items.values():
        if item.location and item.location in world.rooms:
            by_room[item.location]["items"].append(item)
        else:
            unplaced_items.append(item)

    lines.append("#")
    lines.append("# --- Phase 2: describe rooms, link exits, place characters and items ---")
    lines.append("#")

    for room_id, actions in by_room.items():
        room = world.rooms[room_id]
        lines.append(f"@tel {_room_ref(world, room_id)}")
        lines.append("#")

        if room.description:
            lines.append(f"@desc here = \n{room.description.strip()}\n#")

        for ex in actions["exits"]:
            lines.append(f"@open {ex.direction} = {_room_ref(world, ex.to_room)}")
            lines.append("#")
            if ex.locked_until:
                lines.append(f"# NOTE: exit {ex.from_room} -({ex.direction})-> {ex.to_room} should lock on '{ex.locked_until}'.")
                lines.append(f"# @lock <exit-dbref-from-output-above> = traverse:{_lockfunc_guess(ex.locked_until)}")
                lines.append("# ^ lockfunc name is a guess — confirm it exists in the target project, and fill in")
                lines.append("#   the real dbref reported when the @open above ran (batch mode can't self-reference it).")
                lines.append("#")

        for char in actions["characters"]:
            lines.append(f"@create/drop {char.id}:typeclasses.characters.Character")
            lines.append("# ^ typeclass defaults to the project's base Character class — replace with a real NPC")
            lines.append("#   typeclass if one exists. No space around ':' — Evennia's parser breaks on that.")
            lines.append("#")
            if char.title:
                lines.append(f"@name {char.id} = {char.title};{char.id}")
                lines.append("#")

        for item in actions["items"]:
            lines.append(f"@create/drop {item.id}")
            lines.append("#")
            if item.locked_until:
                lines.append(f"# NOTE: item '{item.id}' should lock on '{item.locked_until}'.")
                lines.append(f"# @lock {item.id} = get:{_lockfunc_guess(item.locked_until)}")
                lines.append("#")

    if unplaced_characters or unplaced_items:
        lines.append("#")
        lines.append("# --- Entities the compiler could not place automatically ---")
        for char in unplaced_characters:
            lines.append(f"# character '{char.id}' has no room location (location={char.location!r}) — place manually.")
        for item in unplaced_items:
            if item.location:
                lines.append(
                    f"# item '{item.id}' is carried by character '{item.location}', not placed in a room —"
                    f" batch mode can't 'give' reliably without a live dbref, create and hand it over manually."
                )
            else:
                lines.append(f"# item '{item.id}' has no location at all — place manually.")

    player_starts = [c for c in world.characters.values() if c.role == "player_start"]
    if player_starts:
        lines.append("#")
        lines.append("# --- role=player_start characters (not instantiated — see references/evennia-mapping.md) ---")
        for char in player_starts:
            lines.append(f"# '{char.id}' ({char.title or char.id}) represents where a PLAYER begins, at room"
                          f" '{char.location or world.start_room}'. Evennia's account/character creation flow")
            lines.append(f"# handles spawning a real player character at world.start_room; nothing to generate here.")

    return "\n".join(lines) + "\n"


def _lockfunc_guess(locked_until: str) -> str:
    """Turns 'quest.find_the_key.completed' into 'quest_completed(find_the_key)' —
    a *guess* at a lockfunc call, not a verified one. Always emitted as a comment
    because this compiler has no way to know whether the target Evennia project
    actually defines this lockfunc.
    """
    parts = locked_until.split(".")
    if len(parts) == 3 and parts[0] == "quest" and parts[2] == "completed":
        return f"quest_completed({parts[1]})"
    return f"condition({locked_until})"


def compile_quests_py(world: WorldIR) -> str:
    """Returns the contents of a quests.py data file. Evennia has no built-in
    quest system — this is quest *data* for the target project's own
    quest-tracking code to consume, not a quest engine.
    """
    lines = [
        f"# Generated by world_ir.compile_evennia — world '{world.id}' v{world.version}",
        "# Quest DATA only. Evennia has no built-in quest engine; wire this into",
        "# the target project's own quest-tracking system.",
        "QUESTS = {",
    ]
    for q in world.quests.values():
        lines.append(f"    {q.id!r}: {{")
        lines.append(f"        \"giver\": {q.giver!r},")
        lines.append(f"        \"prerequisites\": {q.prerequisites!r},")
        lines.append(f"        \"steps\": {q.steps!r},")
        lines.append(f"        \"reward\": {q.reward!r},")
        lines.append("    },")
    lines.append("}")
    return "\n".join(lines) + "\n"


def compile_world(world: WorldIR, out_dir: str | Path) -> dict[str, Path]:
    """Compiles a validated World IR to Evennia artifacts under out_dir. Returns
    the paths written. Raises CompileError if the world doesn't validate."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    ev_path = out_dir / f"{world.id}.ev"
    ev_path.write_text(compile_batchcode(world), encoding="utf-8")

    written = {"batchcode": ev_path}

    if world.quests:
        quests_path = out_dir / "quests.py"
        quests_path.write_text(compile_quests_py(world), encoding="utf-8")
        written["quests"] = quests_path

    return written
