# Generated by world_ir.compile_evennia — world 'black_tide_city' v0.1.0
# Quest DATA only. Evennia has no built-in quest engine; wire this into
# the target project's own quest-tracking system.
QUESTS = {
    'find_the_key': {
        "giver": 'old_maren',
        "prerequisites": [],
        "steps": ['pick up rusted_key from south_gate', 'return rusted_key to old_maren'],
        "reward": 'unlocks: vault_antechamber',
    },
}
